### PR TITLE
BART_Prediction

### PR DESCRIPTION
**Pull request by swarooprm**

### CODE REVIEW

**Comment by danyaljj** [comment]
I feel that an example BART prediction will be of little use.

**Comment by swarooprm** [comment]
I can get all BART_Predictions, but I have to do that process manually by downloading files from beaker and then converting them to appropriate json format. It will take some time, let me know if you need that?

**Comment by swarooprm** [comment]
Alternatively we can remove bart_prediction folder from the repo.

**Comment by danyaljj** [comment]
Yeah let's close this PR. We will add BART predictions at a later time.

**Pull request closed without merging**
